### ISSUE TITLE
why no hull?

### ISSUE THREAD

**Issue by tcurdt** [gega/csg2stp#1]
Sorry for just a curious question as "issue" but is there a particular reason why "hull" cannot be supported?

I just stumbled across this reading up on the current state of OpenSCAD step support.

**Comment by gega** [comment]
> Sorry for just a curious question as "issue" but is there a particular reason why "hull" cannot be supported?
> 
> I just stumbled across this reading up on the current state of OpenSCAD step support.

Yes, the reason is that hull is not supported in Open CASCADE. That's the only comprehensive brep library which is open source (as far as I know).

Background of this tool:
The brep representation needed for some applications and this is why I wrote these conversion hacks. I like to design in OpenSCAD but if I would like to make my parts with CNC, they are unable to use the STL format (based on triangles) to create the g-code because the shapes (arcs, circles, etc) are lost and the g-code describes the tool movements which is better if smooth and dense -- ie like the difference between vector graphics and pixel based graphics.

**Comment by tcurdt** [comment]
Thanks for the explanation!

It's a shame that `hull()` is not supported in OpenCSG.

> Background of this tool:
> The brep representation needed for some applications and this is why I wrote these conversion hacks. I like to design in OpenSCAD but if I would like to make my parts with CNC

That's pretty much how I ended up here as well :)

Maybe as a pointer. I just found that exporting in OpenSCAD as CSG and then importing into FreeCAD as CSG works surprisingly well. Except for some bugs I stumbled across.

https://github.com/FreeCAD/FreeCAD/issues/9602

But maybe it still helps you with your workflow as well (once the bugs are fixed).

**Comment by gega** [comment]
Yes, I like FreeCAD too! In fact I stopped using OpenSCAD a while ago in favor of FreeCAD. Unfortunately, for me the CSG import never worked. Actually my workflow only rarely works either, but I can start the script in a loop to do the conversion multiple times during the night and in the morning I just have to choose the one which was successful. This is impossible with a GUI tool.
Also OpenSCAD concept sounds good in theory but any reasonable complex object became extremely complicated and slow to render. One of my objects is rendering in an hour, preview is out of question and the conversion to brep takes one to two nights. FreeCAD is better in this regard even though I prefer the OpenSCAD way.
